### PR TITLE
Small change to compile

### PR DESCRIPTION
**Pull request by AndyZe**
This is a very small change that allows me to compile on Ubuntu 16.04, 64-bit. I'm using the most up-to-date version of openvr, cloned from https://github.com/ValveSoftware/openvr/tree/b72abcebff7e6c6c70ce8ac8f6a09b70d44397e2

I very much appreciate this work!

### CODE REVIEW

**Comment by AndyZe** [comment]
The error before this change was:

```
LighthouseTracking.cpp:437:18: error: ‘class vr::IVRSystem’ has no member named ‘IsInputFocusCapturedByAnotherProcess’
  if (vr_pointer->IsInputFocusCapturedByAnotherProcess())
```

**Comment by offchan42** [comment]
I have this error to on Windows/Cygwin!
image

**Comment by offchan42** [comment]
And also the file was named `compile.bat` not `compile.sh` as shown in the README.
